spring:
  main:
    banner-mode: off
  profiles:
    #    active: producer #use only to run producer
    #    active: consumer #use only to run consumer
    active: produce-consume      #use to run both consumer and producer on the same topic
  kafka:
    bootstrap-servers: efs-ext.event.interop.eus2.blueyonder.dev:9092
    topic-name: tst.eus2.interop.e2e.one-interop-outbound.interop
    group-id: e2e-by-one-integration.test10
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username="test2" password="test3";
        mechanism: PLAIN

logging:
  level:
    root: error
    app: warn
    org.apache.kafka: warn