spring:
  main:
    banner-mode: off
  profiles:
    #    active: producer #use only to run producer
    #    active: consumer #use only to run consumer
    active: all      #use to run both consumer and producer on the same topic
  kafka:
    bootstrap-servers: efs-ext.event.interop.eus2.blueyonder.dev:9092
    topic-name: test.eus2.ef-internal.ef-dev.sample-entity.test-topic
    group-id: test-project-ef-internal-02.test-topic
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        oauthbearer:
          header:
            urlencode: true
          token:
            endpoint:
              url: https://blueyonderinteroptestus.b2clogin.com/blueyonderinteroptestus.onmicrosoft.com/B2C_1A_ClientCredential/oauth2/v2.0/token?realmId=469b8843-60ed-4f70-a1b9-bfc97ad1061e&grant_type=client_credentials&client_id=65be725e-6328-49ed-b2a1-d5d856bdde87&client_secret=0Jf8Q~66NeYv_kX_nLzK3Fo3wXxG6IjZWRsh.aeG&scope=https://blueyonderinteroptestus.onmicrosoft.com/6ad21424-b4b2-462e-80df-252ec22dd6a9/.default
        login:
          callback:
            handler:
              class: org.apache.kafka.common.security.oauthbearer.secured.OAuthBearerLoginCallbackHandler
        jaas:
          config: org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required clientId="65be725e-6328-49ed-b2a1-d5d856bdde87" scope="https://blueyonderinteroptestus.onmicrosoft.com/6ad21424-b4b2-462e-80df-252ec22dd6a9/.default" clientSecret="0Jf8Q~66NeYv_kX_nLzK3Fo3wXxG6IjZWRsh.aeG";
        mechanism: OAUTHBEARER

logging:
  level:
    root: error
    app: warn
    org.apache.kafka: warn