spring:
  main:
    banner-mode: off
  profiles:
    #    active: producer #use only to run producer
    #    active: consumer #use only to run consumer
    active: all      #use to run both consumer and producer on the same topic
  kafka:
    bootstrap-servers: efs-ext.event.interop.eus2.blueyonder.dev:9092
    topic-name: test.eus2.ef-internal.ef-dev.sample-entity.test-topic
    group-id: test-project-ef-internal-02.test-topic
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username="c9987e4a00685859c5357854fd6cea69ac650b3bf4ab0b02d36232919c5d7a0b" password="ca03bede-7349-4f47-b304-4afa2c78269a";
        mechanism: PLAIN

logging:
  level:
    root: error
    app: warn
    org.apache.kafka: warn